" ~/.vimrc (symlink to ./vimrc)

" ---------- Safety / Compat ----------
set nocompatible
scriptencoding utf-8
set encoding=utf-8

" automatically load changed files
set autoread

" auto-reload vimrc
autocmd! bufwritepost vimrc source ~/.vim/vimrc

" show the filename in the window titlebar
set title

" display incomplete commands at the bottom
set showcmd

" line numbers
set number

" highlight cursor line
set cursorline

" wrapping stuff
set textwidth=80
set colorcolumn=80

" status bar
set laststatus=2

" make laggy connections work faster
set ttyfast

" Searching
set hlsearch "when there is a previous search pattern, highlight all its matches
set incsearch "while typing a search command, show immediately where the so far typed pattern matches
set ignorecase "ignore case in search patterns
set smartcase "override the 'ignorecase' option if the search pattern contains uppercase characters
set gdefault "imply global for new searches

" Indenting
set copyindent
set smarttab
set autoindent
set smartindent

" Clipboard
set clipboard=unnamedplus

